name: Server

on:
    push:
        branches: [development]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "npm"
                  cache-dependency-path: server/package-lock.json

            - name: Restore cache
              uses: actions/cache@v4
              with:
                  path: |
                      server/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('server/package-lock.json') }}

            - name: Install dependencies
              run: npm ci
              working-directory: server

            - name: Build with nodejs
              run: npm run build
              working-directory: server

    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: server
                  push: true
                  tags: s3975162/matchworks-server:latest

            - name: Update Portainer Stack
              run: |
                  curl -X POST "$PORTAINER_STACK_WEBHOOK_URL"
